services:
  app:
    build:
      context: .
      dockerfile: SheinPrototype/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: shein
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - C:/Users/Leonardo Bloise/RiderProjects/SheinPrototype/SheinPrototype/nginx.conf:/etc/nginx/nginx.conf  # Adjusted to use relative path for Linux-based container
    depends_on:
      - app
 
